# Generated by Django 4.2 on 2024-10-08 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contactPhone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, unique=True)),
                ('id_hospital', models.ManyToManyField(blank=True, to='api.hospital')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='lastName',
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('doctorId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hospitalId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
                ('id_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='timetables',
            field=models.ManyToManyField(blank=True, to='api.timetable'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='api.room'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='timetables',
            field=models.ManyToManyField(blank=True, to='api.timetable'),
        ),
    ]
