# Generated by Django 4.2 on 2024-09-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='contactPhone',
            field=models.CharField(max_length=11),
        ),
    ]
