# Generated by Django 4.2 on 2024-09-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalId', models.PositiveIntegerField()),
                ('doctorlId', models.PositiveIntegerField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('room', models.CharField(max_length=50)),
            ],
        ),
    ]
