# Generated by Django 4.2 on 2024-09-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='doctorlId',
            new_name='doctorId',
        ),
    ]
