# Generated by Django 4.2 on 2024-09-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='roles',
            field=models.ManyToManyField(blank=True, to='account.role'),
        ),
    ]
