# Generated by Django 4.2 on 2024-09-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='myuser',
            name='roles',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('doctor', 'Doctor'), ('user', 'User')], max_length=50),
        ),
    ]
