# Generated by Django 4.2 on 2024-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_hospitals_alter_room_id_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='api.hospital'),
        ),
    ]
