# Generated by Django 4.2 on 2024-10-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='timetables',
            field=models.ManyToManyField(to='api.timetable'),
        ),
    ]
