# Generated by Django 4.2 on 2024-10-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_hospitals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apointment',
            new_name='Appointment',
        ),
        migrations.AddField(
            model_name='myuser',
            name='appointents',
            field=models.ManyToManyField(blank=True, to='api.appointment'),
        ),
    ]
