# Generated by Django 4.2 on 2024-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hospital_timetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='time_table',
            field=models.ManyToManyField(blank=True, to='api.timetable'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='timetables',
            field=models.ManyToManyField(blank=True, to='api.timetable'),
        ),
    ]
