# Generated by Django 4.2 on 2024-10-07 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_myuser_time_table_alter_hospital_timetables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='time_table',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='timetables',
            field=models.ManyToManyField(blank=True, to='api.timetable'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='id_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='doctorId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='hospitalId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
    ]
