# Generated by Django 4.2 on 2024-10-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_apointment_appointment_myuser_appointents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='appointents',
            new_name='appointments',
        ),
    ]
