# Generated by Django 4.2 on 2024-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_myuser_time_table_remove_timetable_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id_hospital',
            field=models.ManyToManyField(blank=True, to='api.hospital'),
        ),
    ]
