# Generated by Django 4.2 on 2024-10-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_id_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id_hospital',
        ),
        migrations.AddField(
            model_name='room',
            name='id_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
    ]
