# Generated by Django 4.2 on 2024-10-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='history',
            field=models.ManyToManyField(blank=True, to='api.history'),
        ),
    ]
